// source: serviciosStreaming.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.servicios.CancionDTO', null, global);
goog.exportSymbol('proto.servicios.FragmentoCancion', null, global);
goog.exportSymbol('proto.servicios.PeticionStreamDTO', null, global);
goog.exportSymbol('proto.servicios.peticionDTO', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.servicios.peticionDTO = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.servicios.peticionDTO, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.servicios.peticionDTO.displayName = 'proto.servicios.peticionDTO';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.servicios.FragmentoCancion = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.servicios.FragmentoCancion, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.servicios.FragmentoCancion.displayName = 'proto.servicios.FragmentoCancion';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.servicios.PeticionStreamDTO = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.servicios.PeticionStreamDTO, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.servicios.PeticionStreamDTO.displayName = 'proto.servicios.PeticionStreamDTO';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.servicios.CancionDTO = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.servicios.CancionDTO, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.servicios.CancionDTO.displayName = 'proto.servicios.CancionDTO';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.servicios.peticionDTO.prototype.toObject = function(opt_includeInstance) {
  return proto.servicios.peticionDTO.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.servicios.peticionDTO} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.servicios.peticionDTO.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.servicios.peticionDTO}
 */
proto.servicios.peticionDTO.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.servicios.peticionDTO;
  return proto.servicios.peticionDTO.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.servicios.peticionDTO} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.servicios.peticionDTO}
 */
proto.servicios.peticionDTO.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.servicios.peticionDTO.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.servicios.peticionDTO.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.servicios.peticionDTO} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.servicios.peticionDTO.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.servicios.peticionDTO.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.servicios.peticionDTO} returns this
 */
proto.servicios.peticionDTO.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.servicios.FragmentoCancion.prototype.toObject = function(opt_includeInstance) {
  return proto.servicios.FragmentoCancion.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.servicios.FragmentoCancion} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.servicios.FragmentoCancion.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: msg.getData_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.servicios.FragmentoCancion}
 */
proto.servicios.FragmentoCancion.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.servicios.FragmentoCancion;
  return proto.servicios.FragmentoCancion.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.servicios.FragmentoCancion} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.servicios.FragmentoCancion}
 */
proto.servicios.FragmentoCancion.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.servicios.FragmentoCancion.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.servicios.FragmentoCancion.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.servicios.FragmentoCancion} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.servicios.FragmentoCancion.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes data = 1;
 * @return {string}
 */
proto.servicios.FragmentoCancion.prototype.getData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes data = 1;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.servicios.FragmentoCancion.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.servicios.FragmentoCancion.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.servicios.FragmentoCancion} returns this
 */
proto.servicios.FragmentoCancion.prototype.setData = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.servicios.PeticionStreamDTO.prototype.toObject = function(opt_includeInstance) {
  return proto.servicios.PeticionStreamDTO.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.servicios.PeticionStreamDTO} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.servicios.PeticionStreamDTO.toObject = function(includeInstance, msg) {
  var f, obj = {
    idusuario: jspb.Message.getFieldWithDefault(msg, 1, 0),
    cancion: (f = msg.getCancion()) && proto.servicios.CancionDTO.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.servicios.PeticionStreamDTO}
 */
proto.servicios.PeticionStreamDTO.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.servicios.PeticionStreamDTO;
  return proto.servicios.PeticionStreamDTO.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.servicios.PeticionStreamDTO} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.servicios.PeticionStreamDTO}
 */
proto.servicios.PeticionStreamDTO.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIdusuario(value);
      break;
    case 2:
      var value = new proto.servicios.CancionDTO;
      reader.readMessage(value,proto.servicios.CancionDTO.deserializeBinaryFromReader);
      msg.setCancion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.servicios.PeticionStreamDTO.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.servicios.PeticionStreamDTO.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.servicios.PeticionStreamDTO} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.servicios.PeticionStreamDTO.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdusuario();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getCancion();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.servicios.CancionDTO.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 IdUsuario = 1;
 * @return {number}
 */
proto.servicios.PeticionStreamDTO.prototype.getIdusuario = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.servicios.PeticionStreamDTO} returns this
 */
proto.servicios.PeticionStreamDTO.prototype.setIdusuario = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional CancionDTO Cancion = 2;
 * @return {?proto.servicios.CancionDTO}
 */
proto.servicios.PeticionStreamDTO.prototype.getCancion = function() {
  return /** @type{?proto.servicios.CancionDTO} */ (
    jspb.Message.getWrapperField(this, proto.servicios.CancionDTO, 2));
};


/**
 * @param {?proto.servicios.CancionDTO|undefined} value
 * @return {!proto.servicios.PeticionStreamDTO} returns this
*/
proto.servicios.PeticionStreamDTO.prototype.setCancion = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.servicios.PeticionStreamDTO} returns this
 */
proto.servicios.PeticionStreamDTO.prototype.clearCancion = function() {
  return this.setCancion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.servicios.PeticionStreamDTO.prototype.hasCancion = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.servicios.CancionDTO.prototype.toObject = function(opt_includeInstance) {
  return proto.servicios.CancionDTO.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.servicios.CancionDTO} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.servicios.CancionDTO.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    titulo: jspb.Message.getFieldWithDefault(msg, 2, ""),
    autor: jspb.Message.getFieldWithDefault(msg, 3, ""),
    album: jspb.Message.getFieldWithDefault(msg, 4, ""),
    aniolanzamiento: jspb.Message.getFieldWithDefault(msg, 5, 0),
    duracions: jspb.Message.getFieldWithDefault(msg, 6, 0),
    genero: jspb.Message.getFieldWithDefault(msg, 7, ""),
    idioma: jspb.Message.getFieldWithDefault(msg, 8, ""),
    rutaalmacenamiento: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.servicios.CancionDTO}
 */
proto.servicios.CancionDTO.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.servicios.CancionDTO;
  return proto.servicios.CancionDTO.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.servicios.CancionDTO} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.servicios.CancionDTO}
 */
proto.servicios.CancionDTO.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitulo(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAutor(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAlbum(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAniolanzamiento(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDuracions(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setGenero(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setIdioma(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setRutaalmacenamiento(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.servicios.CancionDTO.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.servicios.CancionDTO.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.servicios.CancionDTO} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.servicios.CancionDTO.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getTitulo();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAutor();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAlbum();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAniolanzamiento();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getDuracions();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getGenero();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getIdioma();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getRutaalmacenamiento();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.servicios.CancionDTO.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.servicios.CancionDTO} returns this
 */
proto.servicios.CancionDTO.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string Titulo = 2;
 * @return {string}
 */
proto.servicios.CancionDTO.prototype.getTitulo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.servicios.CancionDTO} returns this
 */
proto.servicios.CancionDTO.prototype.setTitulo = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string Autor = 3;
 * @return {string}
 */
proto.servicios.CancionDTO.prototype.getAutor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.servicios.CancionDTO} returns this
 */
proto.servicios.CancionDTO.prototype.setAutor = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string Album = 4;
 * @return {string}
 */
proto.servicios.CancionDTO.prototype.getAlbum = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.servicios.CancionDTO} returns this
 */
proto.servicios.CancionDTO.prototype.setAlbum = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 AnioLanzamiento = 5;
 * @return {number}
 */
proto.servicios.CancionDTO.prototype.getAniolanzamiento = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.servicios.CancionDTO} returns this
 */
proto.servicios.CancionDTO.prototype.setAniolanzamiento = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 DuracionS = 6;
 * @return {number}
 */
proto.servicios.CancionDTO.prototype.getDuracions = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.servicios.CancionDTO} returns this
 */
proto.servicios.CancionDTO.prototype.setDuracions = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string Genero = 7;
 * @return {string}
 */
proto.servicios.CancionDTO.prototype.getGenero = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.servicios.CancionDTO} returns this
 */
proto.servicios.CancionDTO.prototype.setGenero = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string Idioma = 8;
 * @return {string}
 */
proto.servicios.CancionDTO.prototype.getIdioma = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.servicios.CancionDTO} returns this
 */
proto.servicios.CancionDTO.prototype.setIdioma = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string RutaAlmacenamiento = 9;
 * @return {string}
 */
proto.servicios.CancionDTO.prototype.getRutaalmacenamiento = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.servicios.CancionDTO} returns this
 */
proto.servicios.CancionDTO.prototype.setRutaalmacenamiento = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


goog.object.extend(exports, proto.servicios);
