// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: serviciosStreaming.proto

package serviciosStreaming

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AudioService_EnviarCancionMedianteStream_FullMethodName = "/servicios.AudioService/enviarCancionMedianteStream"
	AudioService_StremearCancion_FullMethodName             = "/servicios.AudioService/stremearCancion"
)

// AudioServiceClient is the client API for AudioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioServiceClient interface {
	// Función de streaming de canción
	EnviarCancionMedianteStream(ctx context.Context, in *PeticionDTO, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FragmentoCancion], error)
	StremearCancion(ctx context.Context, in *PeticionStreamDTO, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FragmentoCancion], error)
}

type audioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioServiceClient(cc grpc.ClientConnInterface) AudioServiceClient {
	return &audioServiceClient{cc}
}

func (c *audioServiceClient) EnviarCancionMedianteStream(ctx context.Context, in *PeticionDTO, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FragmentoCancion], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AudioService_ServiceDesc.Streams[0], AudioService_EnviarCancionMedianteStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PeticionDTO, FragmentoCancion]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioService_EnviarCancionMedianteStreamClient = grpc.ServerStreamingClient[FragmentoCancion]

func (c *audioServiceClient) StremearCancion(ctx context.Context, in *PeticionStreamDTO, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FragmentoCancion], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AudioService_ServiceDesc.Streams[1], AudioService_StremearCancion_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PeticionStreamDTO, FragmentoCancion]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioService_StremearCancionClient = grpc.ServerStreamingClient[FragmentoCancion]

// AudioServiceServer is the server API for AudioService service.
// All implementations must embed UnimplementedAudioServiceServer
// for forward compatibility.
type AudioServiceServer interface {
	// Función de streaming de canción
	EnviarCancionMedianteStream(*PeticionDTO, grpc.ServerStreamingServer[FragmentoCancion]) error
	StremearCancion(*PeticionStreamDTO, grpc.ServerStreamingServer[FragmentoCancion]) error
	mustEmbedUnimplementedAudioServiceServer()
}

// UnimplementedAudioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioServiceServer struct{}

func (UnimplementedAudioServiceServer) EnviarCancionMedianteStream(*PeticionDTO, grpc.ServerStreamingServer[FragmentoCancion]) error {
	return status.Errorf(codes.Unimplemented, "method EnviarCancionMedianteStream not implemented")
}
func (UnimplementedAudioServiceServer) StremearCancion(*PeticionStreamDTO, grpc.ServerStreamingServer[FragmentoCancion]) error {
	return status.Errorf(codes.Unimplemented, "method StremearCancion not implemented")
}
func (UnimplementedAudioServiceServer) mustEmbedUnimplementedAudioServiceServer() {}
func (UnimplementedAudioServiceServer) testEmbeddedByValue()                      {}

// UnsafeAudioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioServiceServer will
// result in compilation errors.
type UnsafeAudioServiceServer interface {
	mustEmbedUnimplementedAudioServiceServer()
}

func RegisterAudioServiceServer(s grpc.ServiceRegistrar, srv AudioServiceServer) {
	// If the following call pancis, it indicates UnimplementedAudioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioService_ServiceDesc, srv)
}

func _AudioService_EnviarCancionMedianteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PeticionDTO)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AudioServiceServer).EnviarCancionMedianteStream(m, &grpc.GenericServerStream[PeticionDTO, FragmentoCancion]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioService_EnviarCancionMedianteStreamServer = grpc.ServerStreamingServer[FragmentoCancion]

func _AudioService_StremearCancion_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PeticionStreamDTO)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AudioServiceServer).StremearCancion(m, &grpc.GenericServerStream[PeticionStreamDTO, FragmentoCancion]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioService_StremearCancionServer = grpc.ServerStreamingServer[FragmentoCancion]

// AudioService_ServiceDesc is the grpc.ServiceDesc for AudioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicios.AudioService",
	HandlerType: (*AudioServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "enviarCancionMedianteStream",
			Handler:       _AudioService_EnviarCancionMedianteStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "stremearCancion",
			Handler:       _AudioService_StremearCancion_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "serviciosStreaming.proto",
}
