// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: serviciosStreaming.proto

package serviciosStreaming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensajes
type PeticionDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeticionDTO) Reset() {
	*x = PeticionDTO{}
	mi := &file_serviciosStreaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeticionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeticionDTO) ProtoMessage() {}

func (x *PeticionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosStreaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeticionDTO.ProtoReflect.Descriptor instead.
func (*PeticionDTO) Descriptor() ([]byte, []int) {
	return file_serviciosStreaming_proto_rawDescGZIP(), []int{0}
}

func (x *PeticionDTO) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FragmentoCancion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Fragmento de audio
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FragmentoCancion) Reset() {
	*x = FragmentoCancion{}
	mi := &file_serviciosStreaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FragmentoCancion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentoCancion) ProtoMessage() {}

func (x *FragmentoCancion) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosStreaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentoCancion.ProtoReflect.Descriptor instead.
func (*FragmentoCancion) Descriptor() ([]byte, []int) {
	return file_serviciosStreaming_proto_rawDescGZIP(), []int{1}
}

func (x *FragmentoCancion) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PeticionStreamDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdUsuario     int32                  `protobuf:"varint,1,opt,name=IdUsuario,proto3" json:"IdUsuario,omitempty"`
	Cancion       *CancionDTO            `protobuf:"bytes,2,opt,name=Cancion,proto3" json:"Cancion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeticionStreamDTO) Reset() {
	*x = PeticionStreamDTO{}
	mi := &file_serviciosStreaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeticionStreamDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeticionStreamDTO) ProtoMessage() {}

func (x *PeticionStreamDTO) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosStreaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeticionStreamDTO.ProtoReflect.Descriptor instead.
func (*PeticionStreamDTO) Descriptor() ([]byte, []int) {
	return file_serviciosStreaming_proto_rawDescGZIP(), []int{2}
}

func (x *PeticionStreamDTO) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *PeticionStreamDTO) GetCancion() *CancionDTO {
	if x != nil {
		return x.Cancion
	}
	return nil
}

// MENSAJES
type CancionDTO struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Titulo             string                 `protobuf:"bytes,2,opt,name=Titulo,proto3" json:"Titulo,omitempty"`
	Autor              string                 `protobuf:"bytes,3,opt,name=Autor,proto3" json:"Autor,omitempty"`
	Album              string                 `protobuf:"bytes,4,opt,name=Album,proto3" json:"Album,omitempty"`
	AnioLanzamiento    int32                  `protobuf:"varint,5,opt,name=AnioLanzamiento,proto3" json:"AnioLanzamiento,omitempty"`
	DuracionS          int32                  `protobuf:"varint,6,opt,name=DuracionS,proto3" json:"DuracionS,omitempty"`
	Genero             string                 `protobuf:"bytes,7,opt,name=Genero,proto3" json:"Genero,omitempty"`
	Idioma             string                 `protobuf:"bytes,8,opt,name=Idioma,proto3" json:"Idioma,omitempty"`
	RutaAlmacenamiento string                 `protobuf:"bytes,9,opt,name=RutaAlmacenamiento,proto3" json:"RutaAlmacenamiento,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CancionDTO) Reset() {
	*x = CancionDTO{}
	mi := &file_serviciosStreaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancionDTO) ProtoMessage() {}

func (x *CancionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosStreaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancionDTO.ProtoReflect.Descriptor instead.
func (*CancionDTO) Descriptor() ([]byte, []int) {
	return file_serviciosStreaming_proto_rawDescGZIP(), []int{3}
}

func (x *CancionDTO) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CancionDTO) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *CancionDTO) GetAutor() string {
	if x != nil {
		return x.Autor
	}
	return ""
}

func (x *CancionDTO) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *CancionDTO) GetAnioLanzamiento() int32 {
	if x != nil {
		return x.AnioLanzamiento
	}
	return 0
}

func (x *CancionDTO) GetDuracionS() int32 {
	if x != nil {
		return x.DuracionS
	}
	return 0
}

func (x *CancionDTO) GetGenero() string {
	if x != nil {
		return x.Genero
	}
	return ""
}

func (x *CancionDTO) GetIdioma() string {
	if x != nil {
		return x.Idioma
	}
	return ""
}

func (x *CancionDTO) GetRutaAlmacenamiento() string {
	if x != nil {
		return x.RutaAlmacenamiento
	}
	return ""
}

var File_serviciosStreaming_proto protoreflect.FileDescriptor

const file_serviciosStreaming_proto_rawDesc = "" +
	"\n" +
	"\x18serviciosStreaming.proto\x12\tservicios\"\x1d\n" +
	"\vpeticionDTO\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\"&\n" +
	"\x10FragmentoCancion\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"b\n" +
	"\x11PeticionStreamDTO\x12\x1c\n" +
	"\tIdUsuario\x18\x01 \x01(\x05R\tIdUsuario\x12/\n" +
	"\aCancion\x18\x02 \x01(\v2\x15.servicios.CancionDTOR\aCancion\"\x88\x02\n" +
	"\n" +
	"CancionDTO\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06Titulo\x18\x02 \x01(\tR\x06Titulo\x12\x14\n" +
	"\x05Autor\x18\x03 \x01(\tR\x05Autor\x12\x14\n" +
	"\x05Album\x18\x04 \x01(\tR\x05Album\x12(\n" +
	"\x0fAnioLanzamiento\x18\x05 \x01(\x05R\x0fAnioLanzamiento\x12\x1c\n" +
	"\tDuracionS\x18\x06 \x01(\x05R\tDuracionS\x12\x16\n" +
	"\x06Genero\x18\a \x01(\tR\x06Genero\x12\x16\n" +
	"\x06Idioma\x18\b \x01(\tR\x06Idioma\x12.\n" +
	"\x12RutaAlmacenamiento\x18\t \x01(\tR\x12RutaAlmacenamiento2\xb4\x01\n" +
	"\fAudioService\x12T\n" +
	"\x1benviarCancionMedianteStream\x12\x16.servicios.peticionDTO\x1a\x1b.servicios.FragmentoCancion0\x01\x12N\n" +
	"\x0fstremearCancion\x12\x1c.servicios.PeticionStreamDTO\x1a\x1b.servicios.FragmentoCancion0\x01B\x15Z\x13/serviciosStreamingb\x06proto3"

var (
	file_serviciosStreaming_proto_rawDescOnce sync.Once
	file_serviciosStreaming_proto_rawDescData []byte
)

func file_serviciosStreaming_proto_rawDescGZIP() []byte {
	file_serviciosStreaming_proto_rawDescOnce.Do(func() {
		file_serviciosStreaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_serviciosStreaming_proto_rawDesc), len(file_serviciosStreaming_proto_rawDesc)))
	})
	return file_serviciosStreaming_proto_rawDescData
}

var file_serviciosStreaming_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_serviciosStreaming_proto_goTypes = []any{
	(*PeticionDTO)(nil),       // 0: servicios.peticionDTO
	(*FragmentoCancion)(nil),  // 1: servicios.FragmentoCancion
	(*PeticionStreamDTO)(nil), // 2: servicios.PeticionStreamDTO
	(*CancionDTO)(nil),        // 3: servicios.CancionDTO
}
var file_serviciosStreaming_proto_depIdxs = []int32{
	3, // 0: servicios.PeticionStreamDTO.Cancion:type_name -> servicios.CancionDTO
	0, // 1: servicios.AudioService.enviarCancionMedianteStream:input_type -> servicios.peticionDTO
	2, // 2: servicios.AudioService.stremearCancion:input_type -> servicios.PeticionStreamDTO
	1, // 3: servicios.AudioService.enviarCancionMedianteStream:output_type -> servicios.FragmentoCancion
	1, // 4: servicios.AudioService.stremearCancion:output_type -> servicios.FragmentoCancion
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_serviciosStreaming_proto_init() }
func file_serviciosStreaming_proto_init() {
	if File_serviciosStreaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_serviciosStreaming_proto_rawDesc), len(file_serviciosStreaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serviciosStreaming_proto_goTypes,
		DependencyIndexes: file_serviciosStreaming_proto_depIdxs,
		MessageInfos:      file_serviciosStreaming_proto_msgTypes,
	}.Build()
	File_serviciosStreaming_proto = out.File
	file_serviciosStreaming_proto_goTypes = nil
	file_serviciosStreaming_proto_depIdxs = nil
}
